### ISSUE TITLE
GEE App Functionality

### ISSUE THREAD

**Issue by mattboddie** [EyeSeeTea/dhis2-gee-app#40]
https://community.dhis2.org/t/gee-app-and-functionality/54033
We’re trying to get the GEE App set up on our servers so that we can start taking pulls of data and pushing it to specific data elements and integrating this data into our analytics. We’ve been able to set up the GEE API Key to allow for Maps to pull and populate data, but are struggling with getting anything meaningful from the GEE App. We keep getting stuck here:

![image](https://github.com/EyeSeeTea/dhis2-gee-app/assets/45822435/351e329a-81f7-41a1-9725-436468994b84)

**Comment by MiquelAdell** [comment]
Hi @mattboddie please check our latest version of the app that solves this exact issue:
https://github.com/EyeSeeTea/dhis2-gee-app-blessed/releases/tag/v1.2.0

thanks!

**Comment by MiquelAdell** [comment]
Hi @mattboddie  please check our latest version of the app that solves this exact issue:
https://github.com/EyeSeeTea/dhis2-gee-app-blessed/releases/tag/v1.2.0

thanks!
